package com.rj.view;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.rj.model.User;
import com.rj.util.Currency;
import com.rj.util.Message;
import com.rj.util.RoundedPanelSwing;

import java.awt.Color;
import java.awt.Cursor;
import java.time.format.DateTimeFormatter;

public class ProfileView extends javax.swing.JPanel {

    /**
     * Creates new form Profile
     */
    public ProfileView() {
        initComponents();
        initStyle();
    }

    private void initStyle() {
        RoundedPanelSwing.applyBorderNoColor(jpProfile, 20, new Color(18, 25, 41));

        // btn imagen de usuario
        FlatSVGIcon image = new FlatSVGIcon(getClass().getResource("/icons/account_circle.svg"));
        lblImage.setIcon(image);
        lblImage.setText("");

        // btn editar
        FlatSVGIcon edit = new FlatSVGIcon(getClass().getResource("/icons/edit.svg"));
        btnEdit.setIcon(edit);
        btnEdit.setToolTipText("Habilitar para Editar");
        btnEdit.setText("");
        btnEdit.setBackground(new Color(214, 137, 16));
        btnEdit.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // btn elminar cuenta
        FlatSVGIcon deleteAccount = new FlatSVGIcon(getClass().getResource("/icons/delete_forever2.svg"));
        btnDeleteAccount.setIcon(deleteAccount);
        btnDeleteAccount.setToolTipText("Eliminar Cuenta");
        btnDeleteAccount.setText("");
        btnDeleteAccount.setBackground(new Color(203, 67, 53));
        btnDeleteAccount.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // btn cambiar contraseña
        FlatSVGIcon changePassword = new FlatSVGIcon(getClass().getResource("/icons/password.svg"));
        btnChangePassword.setIcon(changePassword);
        btnChangePassword.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // btn Egreso
        FlatSVGIcon saveChanges = new FlatSVGIcon(getClass().getResource("/icons/save.svg"));
        btnSaveChanges.setIcon(saveChanges);
        btnSaveChanges.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        lblCurrencySymbolBalance.setText(Currency.currencySymbol());
        lblCurrencySymbolIncome.setText(Currency.currencySymbol());
        lblCurrencySymbolExpense.setText(Currency.currencySymbol());

        // Deshabilitar la edición de los textFields
        txtFirstName.setEditable(false);
        txtLastName.setEditable(false);
        txtUsername.setEditable(false);
        txtKeyword.setEditable(false);

        // Habilitar textFields para editar
        btnEdit.addActionListener((e) -> {
            txtFirstName.setEditable(true);
            txtLastName.setEditable(true);
            txtUsername.setEditable(true);
            txtKeyword.setEditable(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpProfile = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblIncome = new javax.swing.JLabel();
        lblExpense = new javax.swing.JLabel();
        lblCurrencySymbolBalance = new javax.swing.JLabel();
        lblCurrencySymbolIncome = new javax.swing.JLabel();
        lblCurrencySymbolExpense = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAccountCreationDate = new javax.swing.JLabel();
        lblAccountUpdateDate = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        jpProfile.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Imagen");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Nombre completo");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Nombre de usuario");

        jLabel4.setText("Nombre de usuario");

        jLabel5.setText("Nombres");

        jLabel6.setText("Palabra clave de recuperación de cuenta");

        jLabel7.setText("Apellidos");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Perfil");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Saldo");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ingreso");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Egreso");

        lblBalance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(46, 134, 193));
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalance.setText("0.0");

        lblIncome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblIncome.setForeground(new java.awt.Color(23, 165, 137));
        lblIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIncome.setText("0.0");

        lblExpense.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblExpense.setForeground(new java.awt.Color(169, 50, 38));
        lblExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpense.setText("0.0");

        lblCurrencySymbolBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrencySymbolBalance.setText("Symbol");

        lblCurrencySymbolIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrencySymbolIncome.setText("Symbol");

        lblCurrencySymbolExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrencySymbolExpense.setText("Symbol");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fecha de creación");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha de actualización");

        lblAccountCreationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountCreationDate.setText("Fecha");

        lblAccountUpdateDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountUpdateDate.setText("Fecha");

        btnChangePassword.setText("Cambiar contraseña");

        btnSaveChanges.setText("Cuardar cambios");

        btnDeleteAccount.setText("D");

        btnEdit.setText("E");

        javax.swing.GroupLayout jpProfileLayout = new javax.swing.GroupLayout(jpProfile);
        jpProfile.setLayout(jpProfileLayout);
        jpProfileLayout.setHorizontalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProfileLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpProfileLayout.createSequentialGroup()
                        .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProfileLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(lblCurrencySymbolBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(lblIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCurrencySymbolIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(lblExpense, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(lblCurrencySymbolExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProfileLayout.createSequentialGroup()
                                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAccountCreationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(lblAccountUpdateDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProfileLayout.createSequentialGroup()
                                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpProfileLayout.createSequentialGroup()
                                        .addComponent(btnChangePassword)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                                        .addComponent(btnSaveChanges))
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKeyword, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpProfileLayout.createSequentialGroup()
                                        .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jpProfileLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeleteAccount)))
                                .addGap(46, 46, 46))
                            .addGroup(jpProfileLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jpProfileLayout.setVerticalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProfileLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel8)
                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProfileLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProfileLayout.createSequentialGroup()
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsername)
                                .addGap(18, 18, 18)
                                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpProfileLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(lblCurrencySymbolIncome))
                                    .addGroup(jpProfileLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCurrencySymbolBalance))
                                    .addGroup(jpProfileLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(lblCurrencySymbolExpense)))
                                .addGap(97, 97, 97)
                                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAccountCreationDate)
                                    .addComponent(lblAccountUpdateDate)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpProfileLayout.createSequentialGroup()
                        .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteAccount)
                            .addComponent(btnEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChangePassword)
                            .addComponent(btnSaveChanges))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnChangePassword;
    public javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnEdit;
    public javax.swing.JButton btnSaveChanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel jpProfile;
    public javax.swing.JLabel lblAccountCreationDate;
    public javax.swing.JLabel lblAccountUpdateDate;
    public javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCurrencySymbolBalance;
    private javax.swing.JLabel lblCurrencySymbolExpense;
    private javax.swing.JLabel lblCurrencySymbolIncome;
    public javax.swing.JLabel lblExpense;
    private javax.swing.JLabel lblImage;
    public javax.swing.JLabel lblIncome;
    public javax.swing.JLabel lblName;
    public javax.swing.JLabel lblUsername;
    public javax.swing.JTextField txtFirstName;
    public javax.swing.JTextField txtKeyword;
    public javax.swing.JTextField txtLastName;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    /**
     * Obtiene el primer nombre del usuario.
     *
     * @return El primer nombre del usuario.
     */
    public String getFirstName() {
        String firstName = txtFirstName.getText().trim();
        if (firstName.isEmpty()) {
            Message.showWarning("El nombre de usuario no puede estar vacío.");
        }
        return firstName;
    }

    /**
     * Obtiene el apellido del usuario.
     *
     * @return El apellido del usuario.
     */
    public String getLastName() {
        return txtLastName.getText().trim();
    }

    /**
     * Obtiene el nombre de usuario del usuario.
     *
     * @return El nombre de usuario del usuario actual.
     */
    public String getUsername() {
        String username = txtUsername.getText().trim();
        if (username.isEmpty()) {
            Message.showWarning("El nombre de usuario no puede estar vacío.");
        }
        return username;
    }

    /**
     * Obtiene la palabra clave de recuperación de cuenta del usuario.
     *
     * @return La palabra clave de recuperación de cuenta ingresada por el usuario.
     */
    public String getKeyword() {
        String keyword = txtKeyword.getText().trim();
        if (keyword.isEmpty()) {
            Message.showWarning("La palabra clave no puede estar vacía.");
        }
        return keyword;
    }

    /**
     * Valida si algún campo relevante, como nombre de usuario o contraseña, está vacío.
     *
     * @return {@code true} si algún campo está vacío, de lo contrario {@code false}.
     */
    public boolean isFieldsEmpty() {
        return getFirstName().isEmpty() || getLastName().isEmpty() || getUsername().isEmpty() || getKeyword().isEmpty();
    }

    /**
     * Muestra los datos del usuario en el formulario de perfil.
     *
     * @param user El objeto {@link User} que contiene la información del usuario.
     */
    public void profileDetails(User user) {
        String firstName = user.getFirstName();
        String lastName = (user.getLastName() != null) ? user.getLastName() : "";
        double balance = user.getBalance();
        String username = user.getUsername();
        String keyword = user.getKeyword();

        lblName.setText(firstName + " " + lastName);
        lblUsername.setText(username);
        lblBalance.setText(Currency.formatCurrency(balance));
        txtFirstName.setText(firstName);
        txtLastName.setText(lastName);
        txtUsername.setText(username);
        txtKeyword.setText(keyword);

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        lblAccountCreationDate.setText(user.getCreationDate().format(formatter));
        lblAccountUpdateDate.setText(user.getLastUpdate().format(formatter));
    }

    /**
     * Muestra el total de ingresos del usuario.
     *
     * @param totalIncome El total de ingresos que se mostrará.
     */
    public void displayTotalIncome(double totalIncome) {
        lblIncome.setText(Currency.formatCurrency(totalIncome));
    }

    /**
     * Muestra el total de egresos del usuario.
     *
     * @param totalExpense El total de egresos que se mostrará.
     */
    public void displayTotalExpense(double totalExpense) {
        lblExpense.setText(Currency.formatCurrency(totalExpense));
    }
}
